const colors = {
  light: {
    text: "#1F2937",
    tint: "#FF5A00",
    background: "#F8F9FB",
    foreground: "#1F2937",
    card: "#FFFFFF",
    cardForeground: "#1F2937",
    primary: "#FF5A00",
    primaryForeground: "#FFFFFF",
    secondary: "#FF8C42",
    secondaryForeground: "#FFFFFF",
    muted: "#F3F4F6",
    mutedForeground: "#6B7280",
    accent: "#FFF0E8",
    accentForeground: "#FF5A00",
    destructive: "#EF4444",
    destructiveForeground: "#FFFFFF",
    success: "#10B981",
    successForeground: "#FFFFFF",
    border: "#E5E7EB",
    input: "#E5E7EB",
    shadow: "rgba(0,0,0,0.08)",
  },
  dark: {
    text: "#F9FAFB",
    tint: "#FF6B1A",
    background: "#0F1117",
    foreground: "#F9FAFB",
    card: "#1A1D27",
    cardForeground: "#F9FAFB",
    primary: "#FF5A00",
    primaryForeground: "#FFFFFF",
    secondary: "#FF8C42",
    secondaryForeground: "#FFFFFF",
    muted: "#1F2937",
    mutedForeground: "#9CA3AF",
    accent: "#2D1A0E",
    accentForeground: "#FF8C42",
    destructive: "#EF4444",
    destructiveForeground: "#FFFFFF",
    success: "#10B981",
    successForeground: "#FFFFFF",
    border: "#374151",
    input: "#374151",
    shadow: "rgba(0,0,0,0.3)",
  },
  radius: 16,
};

export default colors;
