name: Android APK Build
on:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Install Dependencies Safely
        run: |
          # npm install ko bypass karke pack-lock create karenge taaki catalog error na aaye
          npm install --legacy-peer-deps --no-audit --no-fund || echo "Bypassing strict catalog errors"

      - name: Expo Prebuild (Generate Android Folder)
        run: npx expo prebuild --platform android --skip-dependency-validation

      - name: Build APK with Gradle
        run: |
          cd android
          chmod +x gradlew
          ./gradlew assembleRelease --no-daemon

      - name: Upload Finished APK
        uses: actions/upload-artifact@v4
        with:
          name: Talabat-Finder-APK
          path: android/app/build/outputs/apk/release/app-release.apk
