name: Android APK Build (Expo EAS)
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Install and Build APK
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Setup Expo EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest

      - name: Install dependencies
        run: npm install

      - name: Expo Login and Build Android Preview APK
        run: |
          npx eas-cli login --username "${{ secrets.EXPO_USERNAME }}" --password "${{ secrets.EXPO_PASSWORD }}"
          npx eas-cli build --platform android --profile preview --non-interactive